spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

---
spring:
  profiles: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test-db
    username: test
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hiberate:
        use_sql_comments: true
        show-sql: true

# TODO - production profile
---
spring:
  profiles: production
